---
layout: post
title:  "Docker 实践 - 容器化一个 ASP.NET Core 应用程序"
date:   9999-08-10 01:30:00 +0800
categories: backend docker
published: false
---


In both cases, if the outer task is Faulted or Canceled, there is no inner task, since there’s no result from a task that doesn’t run to completion, so the proxy task then represents the state of the outer task.

在这两种情况下，如果外部任务出错或被取消，则不存在内部任务，因为没有运行到完成的任务不会产生结果，因此代理任务表示外部任务的状态。



https://devblogs.microsoft.com/pfxteam/task-run-vs-task-factory-startnew/